title: Hyunhee Lee 
url: "https://lee-hyunhee.github.io"
baseurl: "/cv/"

markdown: kramdown
#ins_logo: "./Korea-University-logo.jpg"

tracking_id: #

footer: yes
footer_url: "https://lee-hyunhee.github.io/cv/"
footer_text: "Last updated: July 2021"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About Me"
   link: "/cv/"
# - name: "CV"
#   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
